# Generated by Django 5.1 on 2024-08-19 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quote', models.TextField(max_length=555)),
                ('description', models.TextField(max_length=255)),
                ('twitterUrl', models.URLField(blank=True, null=True)),
                ('instagramUrl', models.URLField(blank=True, null=True)),
                ('githubUrl', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
